### ISSUE TITLE
Module build failed: TypeError: fileSystem.statSync is not a function

### ISSUE THREAD

**Issue by iprognos** [lakshmantgld/auth0-APIGateway-customAuthorizer#1]
Just got this error when trying to deploy with sls deploy -v

sls deploy -v
Serverless: Bundling with Webpack...
Time: 517ms

ERROR in ./handler.js
Module build failed: TypeError: fileSystem.statSync is not a function
    at module.exports (/Users/goransvensson/nyics/auth0-APIGateway-CustomAuthorizer/serverless/node_modules/babel-loader/lib/utils/exists.js:7:25)
    at find (/Users/goransvensson/nyics/auth0-APIGateway-CustomAuthorizer/serverless/node_modules/babel-loader/lib/resolve-rc.js:13:9)
    at Object.module.exports (/Users/goransvensson/nyics/auth0-APIGateway-CustomAuthorizer/serverless/node_modules/babel-loader/lib/index.js:111:132)
 
  Error --------------------------------------------------
 
  Webpack compilation error, see above
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           6.7.0
     Serverless Version:     1.25.0

**Comment by iprognos** [comment]
Fixed it by changing index.js line 109 in babel-loader/lib/ 

Before: var fileSystem = this.fs ? this.fs : fs;

After:    var fileSystem = fs;

Not best practice, but it works.

Also updated to latest Serverless and babe-loader v 7.1.4 but it didn't work.
