### ISSUE TITLE
Store and retrive records users has created in a DynamoD?

### ISSUE THREAD

**Issue by appernetic** [lakshmantgld/auth0-APIGateway-customAuthorizer#2]
Silly question! Any advice for best practice to store and retrive records users has created in a DynamoDb. Can I get the principialID (decoded.sub) in the private API. ``` // Private API
module.exports.private = (event, context, callback) => {

pseudo code: add decoded.sub to db table.message

  callback(null, { message: 'Your message has been stored! });
};```

and then add it in a Database write operation, like in my pseudo code?

**Comment by appernetic** [comment]
Maybe I have it in event.requestContext.authorizer.principalId

**Comment by appernetic** [comment]
I have tried with   callback(null, { message: 'Only logged in users can see this ' +  + event.requestContext.authorizer.principalId }); but got error for the authorizer.

Serverless: Uncaught error in your 'private' handler
[ 'TypeError: Cannot read property \'authorizer\' of undefined',
  'at module.exports.private (/home/bror/Documents/NewsApp/auth0-APIGateway-CustomAuthorizer/serverless/handler.js:98:92)',
  'at handler (/home/bror/Documents/NewsApp/auth0-APIGateway-CustomAuthorizer/serverless/node_modules/serverless-offline/src/index.js:815:25)',
  'at Object.internals.handler (/home/bror/Documents/NewsApp/auth0-APIGateway-CustomAuthorizer/serverless/node_modules/hapi/lib/handler.js:96:36)',
  'at request._protect.run (/home/bror/Documents/NewsApp/auth0-APIGateway-CustomAuthorizer/serverless/node_modules/hapi/lib/handler.js:30:23)',
  'at module.exports.internals.Protect.internals.Protect.run (/home/bror/Documents/NewsApp/auth0-APIGateway-CustomAuthorizer/serverless/node_modules/hapi/lib/protect.js:64:5)',

**Comment by appernetic** [comment]
Solved, got it by doing a util inspect first!
